stages:
  - test
  - build
  - deploy

variables:
  ADA_IMAGE: $DOCKER_USER/ada-bot

lint-flake8:
  image: ejplatform/python:alpine
  stage: test
  script:
    - flake8

build ada-bot:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker build -f docker/ada.Dockerfile -t $ADA_IMAGE:homolog .
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker push $ADA_IMAGE:homolog
  only:
    - /devel/

deploy ada-bot-homolog:
  image: cdrx/rancher-gitlab-deploy
  stage: deploy
  script:
    - "upgrade
            --rancher-url $RANCHER_HOMOLOG_URL
            --rancher-key $RANCHER_HOMOLOG_ACCESS_KEY
            --rancher-secret $RANCHER_HOMOLOG_SECRET_KEY
            --environment $RANCHER_ENVIRONMENT
            --stack $RANCHER_STACK
            --service new-ada-bot"
  only:
    - /devel/

