version: '3.7'

services:

  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile-dev
    volumes:
      - './services/api:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig # sets environemnt config
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME="${MONGO_USER}"
      - MONGO_INITDB_ROOT_PASSWORD="${MONGO_PASSWORD}"
      - MONGO_INITDB_DATABASE=${DB_NAME}"

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME="${MONGO_ADMIN_USER}"
      - ME_CONFIG_MONGODB_ADMINPASSWORD="${MONGO_ADMIN_PASSWORD}"